# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fit_multi_models <- function(beta_stage1, se_stage1, W_list, N, n_threads = 1L) {
    .Call('_fungwasStage2_fit_multi_models', PACKAGE = 'fungwasStage2', beta_stage1, se_stage1, W_list, N, n_threads)
}

fit_multi_models_tau_cov <- function(beta_stage1, cov_vec, offsets, W_list, N, n_threads = 1L) {
    .Call('_fungwasStage2_fit_multi_models_tau_cov', PACKAGE = 'fungwasStage2', beta_stage1, cov_vec, offsets, W_list, N, n_threads)
}

#' Compute Calibrated Standard Errors
#' 
#' @param cov_vec Numeric vector containing concatenated upper triangles of covariance matrices.
#' @param offsets Integer vector of byte offsets (0-based) into the original file (needs conversion to index).
#' @param A The transformation matrix (n_params x K).
#' @param K Dimension of the covariance matrix (e.g. 17).
#' @return NumericMatrix of standard errors (n_snps x n_params).
compute_calibrated_se <- function(cov_vec, offsets, A, K) {
    .Call('_fungwasStage2_compute_calibrated_se', PACKAGE = 'fungwasStage2', cov_vec, offsets, A, K)
}

#' Compute parameter covariance upper triangles
#'
#' @param cov_vec Numeric vector containing concatenated upper triangles of covariance matrices.
#' @param offsets Integer vector of byte offsets (0-based) into the original file (needs conversion to index).
#' @param A The transformation matrix (n_params x K).
#' @param K Dimension of the covariance matrix (e.g. 17).
#' @return NumericMatrix of upper-triangle covariance (n_snps x n_cov_params).
compute_param_cov <- function(cov_vec, offsets, A, K) {
    .Call('_fungwasStage2_compute_param_cov', PACKAGE = 'fungwasStage2', cov_vec, offsets, A, K)
}

#' Compute GLS Stage 2 Parameter GWAS
#'
#' Uses the per-SNP tau covariance matrix from Stage 1 to estimate SNP-specific
#' generalized least-squares parameter effects and their covariance.
#'
#' @param beta_stage1 Tau-level SNP effects as a K x n_snps matrix.
#' @param cov_vec Numeric vector containing concatenated upper triangles of covariance matrices.
#' @param offsets Integer vector of byte offsets (0-based) into the original file.
#' @param W Weight/design matrix with K rows and n_params columns.
#' @param return_cov Whether to return parameter covariance upper triangles.
#' @param gls_ridge Relative diagonal ridge added only if the covariance solve fails.
#' @param n_threads Number of OpenMP threads.
#' @return List with params, se, Q, and optionally param_cov_upper.
compute_gls_param_gwas <- function(beta_stage1, cov_vec, offsets, W, return_cov = FALSE, gls_ridge = 1e-8, n_threads = 1L) {
    .Call('_fungwasStage2_compute_gls_param_gwas', PACKAGE = 'fungwasStage2', beta_stage1, cov_vec, offsets, W, return_cov, gls_ridge, n_threads)
}
